import './globals.css'
import type { Metadata } from 'next'
import { Vazirmatn } from 'next/font/google'
import MainHeader from '@/app/home/header/MainHeader'
import FooterNav from './home/nav/FooterNav'

const vazirFont = Vazirmatn({
  subsets: ['latin', 'arabic'],
  variable: '--font-vazir',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' dir='rtl'>
      <body
        className={`${vazirFont.className} select-none min-h-screen bg-snow-white`}
      >
        <main className='container max-w-screen-lg mx-auto relative overflow-hidden'>
          <MainHeader />
          {children}
          <FooterNav />
        </main>
      </body>
    </html>
  )
}
